name: swebench-eval

on:
   workflow_dispatch:
    inputs:
      run_id:
        required: true
        default: 'validate-gold'
      predictions_path:
        required: true
        default: 'gold'
      imageIds:
        required: true
        default: 'sympy__sympy-20590'
      max_workers:
        required: true
        default: '1'  
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: 'Base64 encoded patch content'
        required: false
        default: ''
      command:
        description: 'Base64 encoded command content'
        required: false
        default: ''
      ref:
        description: 'The branch, tag, or commit SHA to checkout'
        required: false
        #default: '9802a2c638ac5cb2be7120651835ffb4f82a8d60' # snapshot from 7/27/24
        default: '7336033d65d32ec62f9ce2419aa8f3a757b06ce2' # snapshot from 8/20/24
      workflow_run_name:
        description: 'A custom name to use for a specific workflow run. You can use a unique name here to later uniquely identify a run before you know its ID. This is just a workaround until GitHub implements a way to get run id directly when kicking off a run: https://github.com/orgs/community/discussions/9752#discussioncomment-10362098'
        required: false
        default: ''
      parse_logs:
        description: 'Runs the repo-specific log parsing logic provided by SWEBench in the function swebench.harness.grading.get_logs_eval()'
        required: false
        default: 'false'
      # Note that GitHub Actions supports a maximum of 10 inputs, so if you need more inputs, you will need to combine inputs: for example, combine them into a single JSON input.


# Note - per the GitHub Actions documentation: "If run-name is omitted or is only whitespace, then the run name is set to event-specific information for the workflow run. For example, for a workflow triggered by a push or pull_request event, it is set as the commit message or the title of the pull request."
run-name: ${{ inputs.workflow_run_name }}
permissions:
      id-token: write
      contents: read      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run_swebench:    
    env:
      REPO_NAME: princeton-nlp/SWE-bench
      REPO_PATH: SWE-bench-repo
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ env.REPO_PATH }}    
    steps:  
    - name: Checkout repository ${{ env.REPO_NAME }}
      uses: actions/checkout@v4
      with:
        repository: ${{ env.REPO_NAME }}
        path: ${{ env.REPO_PATH }}
        ref: ${{ github.event.inputs.ref }}
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install SWE-bench
      run: |
        pip install --upgrade pip wheel
        pip install -e .
    - name: 'Az CLI login'
      if: ${{ github.event.inputs.command != '' }}
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
    - name: Login to ACR
      if: ${{ github.event.inputs.command != '' }}
      run: az acr login --name codeexecservice
    - name: Run SWEBench docker
      if: ${{ github.event.inputs.command != '' }}
      shell: bash
      run: |
            imageId="${{ github.event.inputs.imageIds }}"
            echo "imageid=${imageId}" 
            imageName="sweb.eval.x86_64.${imageId}"
            echo "imageName=${imageName}"
            docker run --name $imageId -d codeexecservice.azurecr.io/${imageName}:latest tail -f /dev/null
            docker ps

    - name: Log local state
      shell: bash
      run: |
          echo "Local docker containers running:"
          docker ps
          echo "Local repo HEAD is at:"
          git log -1
    - name: Apply patch to SWE Bench Container
      if: ${{ github.event.inputs.command != '' }}
      shell: bash
      run: |
          if [ -n "${{ github.event.inputs.patch }}" ]; then
            echo "Patch input provided. Applying patch..."
            echo "${{ github.event.inputs.patch }}" | base64 --decode | sed 's/\r$//'  > patch.diff    
            echo "Decoded patch content:"
            cat patch.diff
            echo "copying patch file..."
            imageId="${{ github.event.inputs.imageIds }}"
            containerName="${imageId}"
            echo "containerName=${containerName}"
            working_dir=$(docker exec $containerName pwd)
            echo "Container workingDir: $working_dir"
            docker cp patch.diff $containerName:${working_dir}/
            echo "Apply the patch:"
            PATCH_OUTPUT=$(docker exec $containerName bash -c "git apply --verbose patch.diff")
            echo "patch Output: $PATCH_OUTPUT"            
          else
            echo "No patch input provided. Skipping patch application."
          fi         

    - name: Create prediction file    
      shell: bash
      run: |
             if [ -n "${{ github.event.inputs.patch }}" ]; then
             echo " "
             echo "Patch input provided."
             
             # Decode the patch input
             decoded_patch=$(echo "${{ github.event.inputs.patch }}"  | base64 --decode | sed 's/\r//g' | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')              
             # Properly create JSON string using a heredoc without extra spaces         
             json_string=$(cat <<EOF
               [
                 {
                   "instance_id": "${{ github.event.inputs.imageIds }}",
                   "model_patch": "$decoded_patch",
                   "model_name_or_path": "genAI"
                 }
               ]
             EOF
               )
      
             # Write the JSON string to a file
             echo "$json_string" > prediction.json
             echo " "
             echo "Prediction file content:"
             
             # Display the content of prediction.json
             cat prediction.json
             echo " "
             else
             echo "No patch input provided. Skipping patch application."
             fi
          
    - name: Run custom command on SWE Bench Container (ces)
      shell: bash
      run: |       
         if [ -n "${{ github.event.inputs.command }}" ]; then
           echo "Start running custom command"         
           echo "${{ github.event.inputs.command }}"
           cmd=$(echo "${{ github.event.inputs.command }}" | base64 --decode | sed 's/\r$//')
           echo "Decoded custom command is:"   
           echo $cmd
           imageId="${{ github.event.inputs.imageIds }}"
           containerName="${imageId}"
           echo "!!=====================================!!"   
           echo "Custom command output:"   
           echo "!!=====================================!!"   
           CMD_OUTPUT=$(docker exec $containerName bash -c "source /opt/miniconda3/bin/activate && conda activate testbed && eval $cmd")
           echo $CMD_OUTPUT
           echo "!!=====================================!!"   
           echo "RAN_CUSTOM_COMMAND=true" >> $GITHUB_ENV
           echo "Finished running custom command!"
           echo "!!== RUN COMPLETED ==!!"
         fi    
    - name: Run swebench harness evaluation (ces)
      if: env.RAN_CUSTOM_COMMAND != 'true'      
      run: |       
        if [ -n "${{ github.event.inputs.patch }}" ]; then
             predictions_path="prediction.json"
        else
             predictions_path="gold"
        fi
        python -m swebench.harness.run_evaluation \
          --predictions_path "$predictions_path" \
          --max_workers ${{ github.event.inputs.max_workers }} \
          --instance_ids ${{ github.event.inputs.imageIds }} \
          --run_id ${{ github.event.inputs.run_id }} \
          --dataset_name "princeton-nlp/SWE-bench_Verified"
          
    - name: Get SWEBench eval test result (ces)
      if: env.RAN_CUSTOM_COMMAND != 'true'
      run: |
        if [ -n "${{ github.event.inputs.patch }}" ]; then
             name="genAI"
        else
             name="gold"
        fi
        echo "ls: "
        ls ./logs/run_evaluation
        echo " "
        ls ./logs/run_evaluation/${{ github.event.inputs.run_id }}
        echo " "       
        ls -R ./logs/run_evaluation/${{ github.event.inputs.run_id }}/$name
        logsDir="./logs/run_evaluation/${{ github.event.inputs.run_id }}/$name/${{ github.event.inputs.imageIds }}"
        if [ -f "$logsDir/patch.diff" ]; then
          echo "patch.diff content begin"
          echo "----------------"
          cat "$logsDir/patch.diff"
          echo " "
          echo "----------------"
          echo "patch.diff content end"
        else
          echo "$logsDir/patch.diff does not exist."
        fi 
        echo "Contents of test log:"
        echo "========================="
        cat "$logsDir/test_output.txt"
        echo "========================="
        
        if [ ${{ github.event.inputs.parse_logs }} == 'true' ]; then
        
        echo "Log parsed with repo-specific parser:"
        echo "========================="

        python3 << 'EOF'
        import json
        from swebench.harness.grading import get_logs_eval

        if __name__ == "__main__":
            log_filepath = "./logs/run_evaluation/${{ github.event.inputs.run_id }}/${{ github.event.inputs.predictions_path }}/${{ github.event.inputs.imageIds }}/test_output.txt"

            # Get the evaluation results
            # Note: This function figures out the specific SWE-Bench repo it's dealing with based on the `imageIds` part of log_filepath (namely, based on the name of the directory where test_output.txt is directly located)
            status_map, success = get_logs_eval(log_filepath)

            if success:
                # Convert the status map to JSON
                json_string = json.dumps(status_map, indent=4)
                print(json_string)
            else:
                print("Error: Failed to parse log file")
        # Note: end-of-file marker must not be indented relative to bash script base indentation. Otherwise it fails.
        EOF
        
        fi
        
        echo "========================="
        echo "!!== RUN COMPLETED ==!!"
